# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cart-transform"
client_id = "0b7c45e5738f70eb45c783def2fe8e96"
application_url = "https://mv-metric-mouse-era.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [
  "https://mv-metric-mouse-era.trycloudflare.com/auth/callback",
  "https://mv-metric-mouse-era.trycloudflare.com/auth/shopify/callback",
  "https://mv-metric-mouse-era.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "better-carts-dev.myshopify.com"
